ssl-mode: REQUIRED
principals:
- name: admin-pod
  domain: admin-pod
  kind: json
- name: auth
  domain: auth
  kind: json
  trust:
  - admin-pod
  - batch
  - batch-driver
  - ci
  - notebook
  - router
  - batch-tests
  - ci-tests
- name: batch
  domain: batch
  kind: json
  trust:
  - admin-pod
  - router
  - ci
  - batch-tests
- name: batch-driver
  domain: batch-driver
  kind: json
  trust:
  - admin-pod
  - batch
- name: ci
  domain: ci
  kind: json
  trust:
  - admin-pod
  - router
  - batch  # callbacks
  - ci-tests
- name: notebook
  domain: notebook
  kind: json
  trust:
  - admin-pod
  - image-fetcher
  - router
- name: gateway
  domain: gateway
  kind: nginx
  trust:
  - admin-pod
- name: router
  domain: router
  kind: nginx
  trust:
  - admin-pod
  - gateway
  - internal-gateway
- name: site
  domain: site
  kind: nginx
  trust:
  - admin-pod
  - router
- name: scorecard
  domain: scorecard
  kind: json
  trust:
  - admin-pod
  - router
- name: image-fetcher
  domain: image-fetcher
  kind: curl
- name: blog
  domain: blog
  kind: nginx
  trust:
  - admin-pod
  - router
- name: query
  domain: query
  kind: json
  trust:
  - admin-pod
  - router
- name: router-resolver
  domain: router-resolver
  kind: json
  trust:
  - admin-pod
  - internal-gateway
  - gateway
- name: internal-gateway
  domain: internal-gateway
  kind: nginx
  trust:
  - admin-pod
- name: batch-tests
  domain: batch-tests
  kind: json
  trust:
  - admin-pod
  - batch
- name: ci-tests
  domain: ci-tests
  kind: json
  trust:
  - admin-pod
  - ci
